FROM debian:12

RUN apt update; \
    apt install -y vsftpd

COPY ./conf/vsftpd.conf /etc/vsftpd.conf
COPY ./tools/setup.sh /
RUN mkdir -p /var/run/vsftpd/empty && chmod 555 /var/run/vsftpd/empty
RUN mkdir -p /var/ftp
EXPOSE 21

CMD ["bash", "./setup.sh"]