FROM debian:12

RUN apt update
RUN apt install -y wget

RUN apt install -y php8.2 php-mysqli php-fpm php-mysql php-common php
COPY ./conf/www.conf /etc/php/8.2/fpm/pool.d

RUn wget "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php"

RUN mv adminer-4.8.1.php /index.php

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080"]